bagging_fraction: 0.6195425484798118
bagging_freq: 4
bin_construct_sample_cnt: 20000000
boost_from_average: false
boosting_type: gbrt
categorical_column:
- 8
- 9
- 10
- 11
- 12
- 14
deterministic: true
early_stopping_round: 30
feature_fraction: 0.4
feature_pre_filter: false
force_row_wise: true
lambda_l1: 5.727264598051453e-06
lambda_l2: 0.0049956152909178654
learning_rate: 0.02
max_bin: 63
max_delta_step: 1.0
metric: rmse
min_child_samples: 20
min_data_in_leaf: 255
num_iterations: 1000
num_leaves: 106
objective: tweedie
seed: 42
tweedie_variance_power: 1.6
